export const SET_USER = "setUser"
export const SET_USER_ID = "setUserId"
export const SET_TOKEN_DATA = "setTokenData"
export const SET_BATCH = "setBatch"
export const SET_ASSIGNMENT = "setAssignment"
export const SET_STAKE_ASSIGNMENTS = "setStakeAssignments"
export const SET_TICKET = "setTicket"
export const SIGN_IN = "isLogged"